app/models/UnitGroup.php
<?php

/**
 * This is the model base class for the table "unitGroup".
 *
 * Columns in table "unitGroup" available as properties of the model:
 * @property string $id
 * @property string $name
 *
 * Relations of table "unitGroup" available as properties of the model:
 * @property Measure[] $measures
 * @property Unit[] $units
 */
class UnitGroup extends CActiveRecord {

	public static function model($className = __CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'unitGroup';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max' => 50),
			array('id, name', 'safe', 'on' => 'search'),
		);
	}

	public function relations() {
		return array(
			'measures' => array(self::HAS_MANY, 'Measure', 'unitGroup_id'),
			'units'    => array(self::HAS_MANY, 'Unit', 'unitGroup_id'),
		);
	}

	public function attributeLabels() {
		return array(
			'id'   => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}

	public function behaviors() {
		return array(
			'CSaveRelationsBehavior', array(
				'class' => 'CSaveRelationsBehavior'
			),
		);
	}

	public function beforeValidate() {
		return parent::beforeValidate();
	}

	public function afterValidate() {
		return parent::afterValidate();
	}

	public function beforeSave() {
		return parent::beforeSave();
	}

	public function afterSave() {
		return parent::afterSave();
	}

	public function __toString() {
		return (string)$this->name;
	}


}

app/controllers/MeasureController.php
<?php

class MeasureController extends Controller {

	#public $layout='//layouts/column2';
	public $defaultAction = "admin";
	public $scenario = "crud";

	public function filters() {
		return array(
			'accessControl',
		);
	}

	public function accessRules() {
		return array(
			array(
				'allow',
				'actions' => array('index', 'view', 'create', 'update', 'admin', 'delete'),
				'roles'   => array('admin'),
			),
			array(
				'deny',
				'users' => array('*'),
			),
		);
	}

	public function beforeAction($action) {
		parent::beforeAction($action);
		// map identifcationColumn to id
		if (!isset($_GET['id']) && isset($_GET['id'])) {
			$model = Measure::model()->find('id = :id', array(
				':id' => $_GET['id']
			));
			if ($model !== null) {
				$_GET['id'] = $model->id;
			} else {
				throw new CHttpException(400);
			}
		}
		if ($this->module !== null) {
			$this->breadcrumbs[$this->module->Id] = array('/'.$this->module->Id);
		}
		return true;
	}

	public function actionView($id) {
		$model = $this->loadModel($id);
		$this->render('view', array('model' => $model,));
	}

	public function actionCreate() {
		$model           = new Measure;
		$model->scenario = $this->scenario;

		$this->performAjaxValidation($model, 'measure-form');

		if (isset($_POST['Measure'])) {
			$model->attributes = $_POST['Measure'];

			if (isset($_POST['Measure']['User']))
				$model->setRelationRecords('users', $_POST['Measure']['User']);
			try {
				if ($model->save()) {
					if (isset($_GET['returnUrl'])) {
						$this->redirect($_GET['returnUrl']);
					} else {
						$this->redirect(array('view', 'id' => $model->id));
					}
				}
			}
			catch (Exception $e) {
				$model->addError('id', $e->getMessage());
			}
		} elseif (isset($_GET['Measure'])) {
			$model->attributes = $_GET['Measure'];
		}

		$this->render('create', array('model' => $model));
	}


	public function actionUpdate($id) {
		$model           = $this->loadModel($id);
		$model->scenario = $this->scenario;

		$this->performAjaxValidation($model, 'measure-form');

		if (isset($_POST['Measure'])) {
			$model->attributes = $_POST['Measure'];

			if (isset($_POST['Measure']['User']))
				$model->setRelationRecords('users', $_POST['Measure']['User']);
			else
				$model->setRelationRecords('users', array());

			try {
				if ($model->save()) {
					if (isset($_GET['returnUrl'])) {
						$this->redirect($_GET['returnUrl']);
					} else {
						$this->redirect(array('view', 'id' => $model->id));
					}
				}
			}
			catch (Exception $e) {
				$model->addError('id', $e->getMessage());
			}
		}

		$this->render('update', array('model' => $model,));
	}

	public function actionEditableSaver() {
		Yii::import('EditableSaver'); //or you can add import 'ext.editable.*' to config
		$es = new EditableSaver('Measure'); // classname of model to be updated
		$es->update();
	}

	public function actionDelete($id) {
		if (Yii::app()->request->isPostRequest) {
			try {
				$this->loadModel($id)->delete();
			}
			catch (Exception $e) {
				throw new CHttpException(500, $e->getMessage());
			}

			if (!isset($_GET['ajax'])) {
				if (isset($_GET['returnUrl'])) {
					$this->redirect($_GET['returnUrl']);
				} else {
					$this->redirect(array('admin'));
				}
			}
		} else
			throw new CHttpException(400, Yii::t('crud', 'Invalid request. Please do not repeat this request again.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Measure');
		$this->render('index', array('dataProvider' => $dataProvider,));
	}

	public function actionAdmin() {
		$model = new Measure('search');
		$model->unsetAttributes();

		if (isset($_GET['Measure'])) {
			$model->attributes = $_GET['Measure'];
		}

		$this->render('admin', array('model' => $model,));
	}

	public function loadModel($id) {
		$model = Measure::model()->findByPk($id);
		if ($model === null)
			throw new CHttpException(404, Yii::t('crud', 'The requested page does not exist.'));
		return $model;
	}

	protected function performAjaxValidation($model) {
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'measure-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

app/controllers/UnitController.php
<?php

class UnitController extends Controller {

	#public $layout='//layouts/column2';
	public $defaultAction = "admin";
	public $scenario = "crud";

	public function filters() {
		return array(
			'accessControl',
		);
	}

	public function accessRules() {
		return array(
			array(
				'allow',
				'actions' => array('index', 'view', 'create', 'update', 'admin', 'delete'),
				'roles'   => array('admin'),
			),
			array(
				'deny',
				'users' => array('*'),
			),
		);
	}

	public function beforeAction($action) {
		parent::beforeAction($action);
		// map identifcationColumn to id
		if (!isset($_GET['id']) && isset($_GET['id'])) {
			$model = Unit::model()->find('id = :id', array(
				':id' => $_GET['id']
			));
			if ($model !== null) {
				$_GET['id'] = $model->id;
			} else {
				throw new CHttpException(400);
			}
		}
		if ($this->module !== null) {
			$this->breadcrumbs[$this->module->Id] = array('/'.$this->module->Id);
		}
		return true;
	}

	public function actionView($id) {
		$model = $this->loadModel($id);
		$this->render('view', array('model' => $model,));
	}

	public function actionCreate() {
		$model           = new Unit;
		$model->scenario = $this->scenario;

		$this->performAjaxValidation($model, 'unit-form');

		if (isset($_POST['Unit'])) {
			$model->attributes = $_POST['Unit'];

			try {
				if ($model->save()) {
					if (isset($_GET['returnUrl'])) {
						$this->redirect($_GET['returnUrl']);
					} else {
						$this->redirect(array('view', 'id' => $model->id));
					}
				}
			}
			catch (Exception $e) {
				$model->addError('id', $e->getMessage());
			}
		} elseif (isset($_GET['Unit'])) {
			$model->attributes = $_GET['Unit'];
		}

		$this->render('create', array('model' => $model));
	}


	public function actionUpdate($id) {
		$model           = $this->loadModel($id);
		$model->scenario = $this->scenario;

		$this->performAjaxValidation($model, 'unit-form');

		if (isset($_POST['Unit'])) {
			$model->attributes = $_POST['Unit'];


			try {
				if ($model->save()) {
					if (isset($_GET['returnUrl'])) {
						$this->redirect($_GET['returnUrl']);
					} else {
						$this->redirect(array('view', 'id' => $model->id));
					}
				}
			}
			catch (Exception $e) {
				$model->addError('id', $e->getMessage());
			}
		}

		$this->render('update', array('model' => $model,));
	}

	public function actionEditableSaver() {
		Yii::import('EditableSaver'); //or you can add import 'ext.editable.*' to config
		$es = new EditableSaver('Unit'); // classname of model to be updated
		$es->update();
	}

	public function actionDelete($id) {
		if (Yii::app()->request->isPostRequest) {
			try {
				$this->loadModel($id)->delete();
			}
			catch (Exception $e) {
				throw new CHttpException(500, $e->getMessage());
			}

			if (!isset($_GET['ajax'])) {
				if (isset($_GET['returnUrl'])) {
					$this->redirect($_GET['returnUrl']);
				} else {
					$this->redirect(array('admin'));
				}
			}
		} else
			throw new CHttpException(400, Yii::t('crud', 'Invalid request. Please do not repeat this request again.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Unit');
		$this->render('index', array('dataProvider' => $dataProvider));
	}

	public function actionAdmin() {
		$model = new Unit('search');
		$model->unsetAttributes();

		if (isset($_GET['Unit'])) {
			$model->attributes = $_GET['Unit'];
		}

		$this->render('admin', array('model' => $model,));
	}

	public function loadModel($id) {
		$model = Unit::model()->findByPk($id);
		if ($model === null)
			throw new CHttpException(404, Yii::t('crud', 'The requested page does not exist.'));
		return $model;
	}

	protected function performAjaxValidation($model) {
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'unit-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

app/controllers/UnitGroupController.php
<?php

class UnitGroupController extends Controller {

	#public $layout='//layouts/column2';
	public $defaultAction = "admin";
	public $scenario = "crud";

	public function filters() {
		return array(
			'accessControl',
		);
	}

	public function accessRules() {
		return array(
			array(
				'allow',
				'actions' => array('create', 'editableSaver', 'update', 'delete', 'admin', 'view'),
				'roles'   => array('admin'),
			),
			array(
				'deny',
				'users' => array('*'),
			),
		);
	}

	public function beforeAction($action) {
		parent::beforeAction($action);
		// map identifcationColumn to id
		if (!isset($_GET['id']) && isset($_GET['id'])) {
			$model = UnitGroup::model()->find('id = :id', array(
				':id' => $_GET['id']
			));
			if ($model !== null) {
				$_GET['id'] = $model->id;
			} else {
				throw new CHttpException(400);
			}
		}
		if ($this->module !== null) {
			$this->breadcrumbs[$this->module->Id] = array('/'.$this->module->Id);
		}
		return true;
	}

	public function actionView($id) {
		$model = $this->loadModel($id);
		$this->render('view', array('model' => $model,));
	}

	public function actionCreate() {
		$model           = new UnitGroup;
		$model->scenario = $this->scenario;

		$this->performAjaxValidation($model, 'unit-group-form');

		if (isset($_POST['UnitGroup'])) {
			$model->attributes = $_POST['UnitGroup'];

			try {
				if ($model->save()) {
					if (isset($_GET['returnUrl'])) {
						$this->redirect($_GET['returnUrl']);
					} else {
						$this->redirect(array('view', 'id' => $model->id));
					}
				}
			}
			catch (Exception $e) {
				$model->addError('id', $e->getMessage());
			}
		} elseif (isset($_GET['UnitGroup'])) {
			$model->attributes = $_GET['UnitGroup'];
		}

		$this->render('create', array('model' => $model));
	}


	public function actionUpdate($id) {
		$model           = $this->loadModel($id);
		$model->scenario = $this->scenario;

		$this->performAjaxValidation($model, 'unit-group-form');

		if (isset($_POST['UnitGroup'])) {
			$model->attributes = $_POST['UnitGroup'];


			try {
				if ($model->save()) {
					if (isset($_GET['returnUrl'])) {
						$this->redirect($_GET['returnUrl']);
					} else {
						$this->redirect(array('view', 'id' => $model->id));
					}
				}
			}
			catch (Exception $e) {
				$model->addError('id', $e->getMessage());
			}
		}

		$this->render('update', array('model' => $model,));
	}

	public function actionEditableSaver() {
		Yii::import('EditableSaver'); //or you can add import 'ext.editable.*' to config
		$es = new EditableSaver('UnitGroup'); // classname of model to be updated
		$es->update();
	}

	public function actionDelete($id) {
		if (Yii::app()->request->isPostRequest) {
			try {
				$this->loadModel($id)->delete();
			}
			catch (Exception $e) {
				throw new CHttpException(500, $e->getMessage());
			}

			if (!isset($_GET['ajax'])) {
				if (isset($_GET['returnUrl'])) {
					$this->redirect($_GET['returnUrl']);
				} else {
					$this->redirect(array('admin'));
				}
			}
		} else
			throw new CHttpException(400, Yii::t('crud', 'Invalid request. Please do not repeat this request again.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('UnitGroup');
		$this->render('index', array('dataProvider' => $dataProvider,));
	}

	public function actionAdmin() {
		$model = new UnitGroup('search');
		$model->unsetAttributes();

		if (isset($_GET['UnitGroup'])) {
			$model->attributes = $_GET['UnitGroup'];
		}

		$this->render('admin', array('model' => $model,));
	}

	public function loadModel($id) {
		$model = UnitGroup::model()->findByPk($id);
		if ($model === null)
			throw new CHttpException(404, Yii::t('crud', 'The requested page does not exist.'));
		return $model;
	}

	protected function performAjaxValidation($model) {
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'unit-group-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

app/views/unitGroup/_form.php
<div class="form">
	<p class="note">
		<?php echo Yii::t('crud', 'Fields with');?> <span
			class="required">*</span> <?php echo Yii::t('crud', 'are required');?>        .
	</p>


	<?php
	$this->widget('echosen.EChosen',
		array('target' => 'select')
	);
	?>    <?php
	$form = $this->beginWidget('CActiveForm', array(
		'id'                     => 'unit-group-form',
		'enableAjaxValidation'   => true,
		'enableClientValidation' => true,
	));

	echo $form->errorSummary($model);
	?>

	<div class="row">
		<?php echo $form->labelEx($model, 'name'); ?>

		<?php echo $form->textField($model, 'name', array('size' => 50, 'maxlength' => 50)); ?>
		<?php echo $form->error($model, 'name'); ?>
		<?php if ('help.name' != $help = Yii::t('crud', 'help.name')) {
			echo "<span class='help-block'>$help</span>";
		} ?>
	</div>
</div> <!-- form -->

<div class="form-actions">
	<?php
	echo CHtml::Button(Yii::t('crud', 'Cancel'), array(
		'submit' => (isset($_GET['returnUrl'])) ? $_GET['returnUrl'] : array('unitgroup/admin'),
		'class'  => 'btn'
	));
	echo ' '.CHtml::submitButton(Yii::t('crud', 'Save'), array(
		'class' => 'btn btn-primary'
	));
	$this->endWidget(); ?>
</div>

app/views/unitGroup/_search.php
<div class="wide form">

    <?php $form=$this->beginWidget('CActiveForm', array(
        'action'=>Yii::app()->createUrl($this->route),
        'method'=>'get',
)); ?>

                    <div class="row">
            <?php echo $form->label($model,'id'); ?>
                            <?php echo $form->textField($model,'id',array('size'=>10,'maxlength'=>10)); ?>
                    </div>

                    <div class="row">
            <?php echo $form->label($model,'name'); ?>
                            <?php echo $form->textField($model,'name',array('size'=>50,'maxlength'=>50)); ?>
                    </div>

        <div class="row buttons">
        <?php echo CHtml::submitButton(Yii::t('crud', 'Search')); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- search-form -->

app/views/unitGroup/_toolbar.php
<div class="btn-toolbar">
    <div class="btn-group">
        <?php  ?><?php
            switch($this->action->id) {
                case "create":
                    $this->widget("bootstrap.widgets.TbButton", array(
                        "label"=>"Manage",
                        "icon"=>"icon-list-alt",
                        "url"=>array("admin")
                    ));
                    break;
                case "admin":
                    $this->widget("bootstrap.widgets.TbButton", array(
                        "label"=>"Create",
                        "icon"=>"icon-plus",
                        "url"=>array("create")
                    ));
                    break;
                case "view":
                    $this->widget("bootstrap.widgets.TbButton", array(
                        "label"=>"Manage",
                        "icon"=>"icon-list-alt",
                        "url"=>array("admin")
                    ));
                    $this->widget("bootstrap.widgets.TbButton", array(
                        "label"=>"Update",
                        "icon"=>"icon-edit",
                        "url"=>array("update","id"=>$model->{$model->tableSchema->primaryKey})
                    ));
                    $this->widget("bootstrap.widgets.TbButton", array(
                        "label"=>"Create",
                        "icon"=>"icon-plus",
                        "url"=>array("create")
                    ));
                    $this->widget("bootstrap.widgets.TbButton", array(
                        "label"=>"Delete",
                        "type"=>"danger",
                        "icon"=>"icon-remove icon-white",
                        "htmlOptions"=> array(
                            "submit"=>array("delete","id"=>$model->{$model->tableSchema->primaryKey}, "returnUrl"=>Yii::app()->request->getParam("returnUrl")),
                            "confirm"=>"Do you want to delete this item?")
                         )
                    );
                    break;
                case "update":
                    $this->widget("bootstrap.widgets.TbButton", array(
                        "label"=>"Manage",
                        "icon"=>"icon-list-alt",
                        "url"=>array("admin")
                    ));
                    $this->widget("bootstrap.widgets.TbButton", array(
                        "label"=>"View",
                        "icon"=>"icon-eye-open",
                        "url"=>array("view","id"=>$model->{$model->tableSchema->primaryKey})
                    ));
                    $this->widget("bootstrap.widgets.TbButton", array(
                        "label"=>"Delete",
                        "type"=>"danger",
                        "icon"=>"icon-remove icon-white",
                        "htmlOptions"=> array(
                            "submit"=>array("delete","id"=>$model->{$model->tableSchema->primaryKey}, "returnUrl"=>Yii::app()->request->getParam("returnUrl")),
                            "confirm"=>"Do you want to delete this item?")
                         )
                    );
                    break;
            }
        ?>    </div>
    <?php if($this->action->id == 'admin'): ?>    <div class="btn-group">
        <?php
    $this->widget("bootstrap.widgets.TbButton", array(
                        "label"=>"Search",
                        "icon"=>"icon-search",
                        "htmlOptions"=>array("class"=>"search-button")
                    ));?>    </div>

            <div class="btn-group">
            <?php $this->widget('bootstrap.widgets.TbButtonGroup', array(
        'buttons'=>array(
                array('label'=>'Relations', 'icon'=>'icon-search', 'items'=>array(array('label'=>'measures - Measure', 'url' =>array('measure/admin')),array('label'=>'units - Unit', 'url' =>array('unit/admin')),
            )
          ),
        ),
    ));
?>        </div>

        
    <?php endif; ?></div>

<?php if($this->action->id == 'admin'): ?><div class="search-form" style="display:none">
    <?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div>
<?php endif; ?>

app/views/unitGroup/admin.php
<?php
$this->breadcrumbs[] = 'Unit Groups';


Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
$('.search-form').toggle();
return false;
});
$('.search-form form').submit(function(){
$.fn.yiiGridView.update('unit-group-grid', {
data: $(this).serialize()
});
return false;
});
");
?>

<?php $this->widget("TbBreadcrumbs", array("links" => $this->breadcrumbs)) ?>
<h1>
	<?php echo Yii::t('crud', 'Unit Groups'); ?>
	<small><?php echo Yii::t('crud', 'Manage'); ?></small>
</h1>

<?php $this->renderPartial("_toolbar", array("model" => $model)); ?>
<?php $this->widget('TbGridView', [
	'id'           => 'unit-group-grid',
	'type'         => ['striped', 'hover'],
	'dataProvider' => $model->search(),
	'filter'       => $model,
	'pager'        => [
		'class'               => 'TbPager',
		'displayFirstAndLast' => true,
	],
	'columns'=> array(
	'id',
	'name',
	array(
		'class'           => 'TbButtonColumn',
		'viewButtonUrl'   => "Yii::app()->controller->createUrl('view', array('id' => \$data->id))",
		'updateButtonUrl' => "Yii::app()->controller->createUrl('update', array('id' => \$data->id))",
		'deleteButtonUrl' => "Yii::app()->controller->createUrl('delete', array('id' => \$data->id))",
	),
),]) ; ?>

app/views/unitGroup/create.php
<?php
$this->breadcrumbs['Unit Groups'] = array('admin');
$this->breadcrumbs[] = Yii::t('crud', 'Create');
?>
<?php $this->widget("TbBreadcrumbs", array("links"=>$this->breadcrumbs)) ?>
<h1>
    <?php echo Yii::t('crud', 'Unit Group'); ?> <small><?php echo Yii::t('crud', 'Create'); ?></small></h1>

<?php $this->renderPartial("_toolbar", array("model"=>$model)); ?>
<?php
$this->renderPartial('_form', array(
'model' => $model,
'buttons' => 'create'));

?>

app/views/unitGroup/update.php
<?php
$this->breadcrumbs['Unit Groups'] = array('admin');
$this->breadcrumbs[$model->{$model->tableSchema->primaryKey}] = array('view','id'=>$model->{$model->tableSchema->primaryKey});
$this->breadcrumbs[] = Yii::t('crud', 'Update');
?>
<?php $this->widget("TbBreadcrumbs", array("links"=>$this->breadcrumbs)) ?>
<h1>
    Unit Group <small>Update #<?php echo $model->id ?></small></h1>

<?php $this->renderPartial("_toolbar", array("model"=>$model)); ?>
<?php
$this->renderPartial('_form', array(
'model'=>$model));
?>

app/views/unitGroup/view.php
<?php
$this->breadcrumbs['Unit Groups'] = array('admin');
$this->breadcrumbs[] = $model->id;
?>
<?php $this->widget("TbBreadcrumbs", array("links"=>$this->breadcrumbs)) ?>
<h1>
    Unit Group <small>View #<?php echo $model->id ?></small></h1>



<?php $this->renderPartial("_toolbar", array("model"=>$model)); ?>

<h2>
    Data
</h2>

<p>
    <?php
    $this->widget('TbDetailView', array(
    'data'=>$model,
    'attributes'=>array(
            'id',
        'name',
),
        )); ?></p>


<h2>
    Relations
</h2>

<div class='well'>
    <div class='row'>
<div class='span3'><?php $this->widget('bootstrap.widgets.TbButtonGroup', array(
        'type'=>'', // '', 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
        'buttons'=>array(
            array('label'=>'measures', 'icon'=>'icon-list-alt', 'url'=> array('measure/admin')),
                array('icon'=>'icon-plus', 'url'=>array('measure/create', 'Measure' => array('unitGroup_id'=>$model->{$model->tableSchema->primaryKey}))),
        ),
    )); ?></div><div class='span8'>
<?php
    echo '<span class=label>CHasManyRelation</span>';
    if (is_array($model->measures)) {

        echo CHtml::openTag('ul');
            foreach($model->measures as $relatedModel) {

                echo '<li>';
                echo CHtml::link($relatedModel->name, array('measure/view','id'=>$relatedModel->id), array('class'=>''));

                echo '</li>';
            }
        echo CHtml::closeTag('ul');
    }
?></div>
     </div> <!-- row -->
</div> <!-- well -->
<div class='well'>
    <div class='row'>
<div class='span3'><?php $this->widget('bootstrap.widgets.TbButtonGroup', array(
        'type'=>'', // '', 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
        'buttons'=>array(
            array('label'=>'units', 'icon'=>'icon-list-alt', 'url'=> array('unit/admin')),
                array('icon'=>'icon-plus', 'url'=>array('unit/create', 'Unit' => array('unitGroup_id'=>$model->{$model->tableSchema->primaryKey}))),
        ),
    )); ?></div><div class='span8'>
<?php
    echo '<span class=label>CHasManyRelation</span>';
    if (is_array($model->units)) {

        echo CHtml::openTag('ul');
            foreach($model->units as $relatedModel) {

                echo '<li>';
                echo CHtml::link($relatedModel->name, array('unit/view','id'=>$relatedModel->id), array('class'=>''));

                echo '</li>';
            }
        echo CHtml::closeTag('ul');
    }
?></div>
     </div> <!-- row -->
</div> <!-- well -->